version: '3.8'

services:
  upqc-simulation-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upqc-simulation-platform
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
